### ISSUE TITLE
does not set the column width once the streamwrite has been flushed

### ISSUE THREAD

**Issue by rbucker** [qax-os/excelize#1010]
https://github.com/qax-os/excelize/blob/933159f9391f9be1b41b51e85885722124f8a7aa/col.go#L454

I will not know the max width of my columns until I have read the data from the database query... and while the streamwrite seems to expect that the column width is set before the first row is written to the sheet... so I figured I could flush the streamwriter then use the file.setcolwidth() but that did not work.

**Comment by xuri** [comment]
Thanks for your issue, if so, please consider using the normal API instead of streaming API.

**Comment by rbucker** [comment]
I tried this a number of different ways. I tried using file.setcolwidth() while writing to the stream and after I closed the stream. Nothing worked.

**Comment by xuri** [comment]
As stated in the [documentation](https://pkg.go.dev/github.com/xuri/excelize/v2#File.NewStreamWriter), the common API and stream API can't be work mixed to writing data on the worksheets, this issue is similar to issues #725, #777 and #826, you should be call [`streamWriter.SetColWidth`](https://pkg.go.dev/github.com/xuri/excelize/v2#StreamWriter.SetColWidth) instead of [`f.SetColWidth`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.SetColWidth) in the streaming mode.
