### ISSUE TITLE
undefined: strconv.ParseComplex

### ISSUE THREAD

**Issue by oscarict** [qax-os/excelize#1165]
When I try to install, this error  i get 
undefined: strconv.ParseComplex
![image](https://user-images.githubusercontent.com/100735351/156268890-210a1c2f-2cb4-4c89-b295-4de8b17be052.png)

**Comment by xuri** [comment]
This issue duplicate with #815, #816, #820, #836 and #884, since [v2.4.0](https://github.com/xuri/excelize/releases/tag/v2.4.0) (commit [`f8f699`](https://github.com/xuri/excelize/commit/f8f699a172bd0219a8736b19091dd3eaa9eb3b25)), for complex number support required, the requirements Go language version is 1.15 or later.

**Comment by xuri** [comment]
I will close this issue. If you still have any questions, please let me know.
