### ISSUE TITLE
How to get a cell drop list?

### ISSUE THREAD

**Issue by 3xxx** [qax-os/excelize#1191]
Hello excelize team：
Llike [example 3](https://xuri.me/excelize/en/data.html#AddDataValidation),after 
```
dvRange.SetDropList([]string{"1", "2", "3"})
f.AddDataValidation("Sheet1", dvRange)
```
I want get droplist {"1", "2", "3"},can you give me any advices how to read them?

I try in excel vba
`MsgBox (Range("c1").Validation.Formula1)`
It can show `1,2,3`

**Comment by xuri** [comment]
This library doesn't support getting data validation rules currently.

**Comment by xuri** [comment]
Hi @3xxx, sorry for the late reply. Excelize library support get data validation rules by the [`GetDataValidation`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetDataValidations) function since [v2.7.0](https://github.com/xuri/excelize/releases/tag/v2.7.0). You can get drop list value from the formula1 like this:

```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f := excelize.NewFile()
    defer func() {
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()
    dv := excelize.NewDataValidation(true)
    dv.Sqref = "A5:B6"
    dv.SetDropList([]string{"1", "2", "3"})
    if err := f.AddDataValidation("Sheet1", dv); err != nil {
        fmt.Println(err)
        return
    }
    rules, err := f.GetDataValidations("Sheet1")
    if err != nil {
        fmt.Println(err)
        return
    }
    for _, rule := range rules {
        if rule.Sqref == "A5:B6" {
            fmt.Println(rule.Formula1)
        }
    }
    if err := f.SaveAs("Book1.xlsx"); err != nil {
        fmt.Println(err)
    }
}
```

I closed this issue. If you have any questions, please let me know and you can reopen this anytime.
