### ISSUE TITLE
I want set HorizontalCentered but, I can't find related functions.

### ISSUE THREAD

**Issue by yanxianli0526** [qax-os/excelize#1358]
As the title, Please how can I solve it, thanks.

**Comment by xuri** [comment]
Please reference the documentation, you can create a style with center horizontal alignment like this:


```go
styleID, err := f.NewStyle(&excelize.Style{
    Alignment: &excelize.Alignment{Horizontal: "center"},
})
if err != nil {
    fmt.Println(err)
    return
}
if err = f.SetCellStyle("Sheet1", "A1", "A1", styleID); err != nil {
    fmt.Println(err)
    return
}
```

**Comment by yanxianli0526** [comment]
I'm sorry I didn't express it well, this should be what I want to ask thanks
![1663833407784](https://user-images.githubusercontent.com/54883112/191690841-7f89f77d-9f94-4b5c-9984-cb4f72b8ec23.jpg)

**Comment by xuri** [comment]
Thanks for your feedback. This library doesn't support this feature currently, I'll consider adding support for it later.

**Comment by yanxianli0526** [comment]
Thanks,I really need this.

**Comment by xuri** [comment]
I have add set horizontal centered support for this library, but this made a refactor with breaking changes:

# Motivation and Context

When I decided to add set horizontal centered support for this library to resolve #1358, the reason I made this huge breaking change was:

- There are too many exported types for set sheet view, properties, and format properties, although a function using the functional options pattern can be optimized by returning an anonymous function, these types or property set or get function has no binding categorization, so I change these functions like `SetAppProps` to accept a pointer of options structure.
- Users can not easily find out which properties should be in the `SetSheetPrOptions` or `SetSheetFormatPr` categories
- Nested properties cannot proceed modify easily

## Introduce 5 new export data types

`HeaderFooterOptions`, `PageLayoutMarginsOptions`, `PageLayoutOptions`, `SheetPropsOptions`, and `ViewOptions`

## Rename 4 exported data types

- Rename `PivotTableOption` to `PivotTableOptions`
- Rename `FormatHeaderFooter` to `HeaderFooterOptions`
- Rename `FormatSheetProtection` to `SheetProtectionOptions`
- Rename `SparklineOption` to `SparklineOptions`

## Remove 54 exported types

`AutoPageBreaks`, `BaseColWidth`, `BlackAndWhite`, `CodeName`, `CustomHeight`, `Date1904`, `DefaultColWidth`, `DefaultGridColor`, `DefaultRowHeight`, `EnableFormatConditionsCalculation`, `FilterPrivacy`, `FirstPageNumber`, `FitToHeight`, `FitToPage`, `FitToWidth`, `OutlineSummaryBelow`, `PageLayoutOption`, `PageLayoutOptionPtr`, `PageLayoutOrientation`, `PageLayoutPaperSize`, `PageLayoutScale`, `PageMarginBottom`, `PageMarginFooter`, `PageMarginHeader`, `PageMarginLeft`, `PageMarginRight`, `PageMarginsOptions`, `PageMarginsOptionsPtr`, `PageMarginTop`, `Published`, `RightToLeft`, `SheetFormatPrOptions`, `SheetFormatPrOptionsPtr`, `SheetPrOption`, `SheetPrOptionPtr`, `SheetViewOption`, `SheetViewOptionPtr`, `ShowFormulas`, `ShowGridLines`, `ShowRowColHeaders`, `ShowRuler`, `ShowZeros`, `TabColorIndexed`, `TabColorRGB`, `TabColorTheme`, `TabColorTint`, `ThickBottom`, `ThickTop`, `TopLeftCell`, `View`, `WorkbookPrOption`, `WorkbookPrOptionPtr`, `ZeroHeight` and `ZoomScale`

## Remove 2 exported constants

`OrientationPortrait` and `OrientationLandscape`

## Change 8 functions

- Change the `func (f *File) SetPageLayout(sheet string, opts ...PageLayoutOption) error` to `func (f *File) SetPageLayout(sheet string, opts *PageLayoutOptions) error`
- Change the `func (f *File) GetPageLayout(sheet string, opts ...PageLayoutOptionPtr) error` to `func (f *File) GetPageLayout(sheet string) (PageLayoutOptions, error)`
- Change the `func (f *File) SetPageMargins(sheet string, opts ...PageMarginsOptions) error` to `func (f *File) SetPageMargins(sheet string, opts *PageLayoutMarginsOptions) error`
- Change the `func (f *File) GetPageMargins(sheet string, opts ...PageMarginsOptionsPtr) error` to `func (f *File) GetPageMargins(sheet string) (PageLayoutMarginsOptions, error)`
- Change the `func (f *File) SetSheetViewOptions(sheet string, viewIndex int, opts ...SheetViewOption) error` to `func (f *File) SetSheetView(sheet string, viewIndex int, opts *ViewOptions) error`
- Change the `func (f *File) GetSheetViewOptions(sheet string, viewIndex int, opts ...SheetViewOptionPtr) error` to `func (f *File) GetSheetView(sheet string, viewIndex int) (ViewOptions, error)`
- Change the `func (f *File) SetWorkbookPrOptions(opts ...WorkbookPrOption) error` to `func (f *File) SetWorkbookProps(opts *WorkbookPropsOptions) error`
- Change the `func (f *File) GetWorkbookPrOptions(opts ...WorkbookPrOptionPtr) error` to `func (f *File) GetWorkbookProps() (WorkbookPropsOptions, error)`

## Introduce new function to instead of existing functions

- New function `func (f *File) SetSheetProps(sheet string, opts *SheetPropsOptions) error` instead of `func (f *File) SetSheetPrOptions(sheet string, opts ...SheetPrOption) error` and `func (f *File) SetSheetFormatPr(sheet string, opts ...SheetFormatPrOptions) error`
- New function `func (f *File) GetSheetProps(sheet string) (SheetPropsOptions, error)` instead of `func (f *File) GetSheetPrOptions(sheet string, opts ...SheetPrOptionPtr) error` and `func (f *File) GetSheetFormatPr(sheet string, opts ...SheetFormatPrOptionsPtr) error`

Now you can set horizontal centered like this:

```go
enable := true
if err := f.SetPageMargins("Sheet1", &excelize.PageLayoutMarginsOptions{
    Horizontally: &enable,
}); err != nil {
    fmt.Println(err)
}
```
