### ISSUE TITLE
How can I get the general date format

### ISSUE THREAD

**Issue by d630200x** [qax-os/excelize#1363]
When I parse the file, I will get different time formats, such as excel time or others.

Is there a way to get a unified format that I expect?

**Comment by xuri** [comment]
Thanks for your feedback. This issue is similar with #62, #660, #675, #759, #1055, #1258. The Excelize not support to parse all the number formats of the cell currently. This feature are working in progress. As the documentation says, if the cell format can be applied to the value of a cell, the applied value will be returned, otherwise the original value will be returned. I think this can be close this and merge it into issue #660 is still discussing this feature.

**Comment by xuri** [comment]
Hi @d630200x, I closed this issue. If you have any questions, please let me know to reopen this anytime.
