### ISSUE TITLE
type of string cell written by stream writer cannot be shared string

### ISSUE THREAD

**Issue by eaglexiang** [qax-os/excelize#1377]
**Description**

We find the default `Type` of string cell is `str` which means `formula string`. Is there any reason let `excelize` handle it like this? How can I set it as `s`( meaning `shared string`) with stream writer?

https://github.com/qax-os/excelize/blob/14c6a198ce27b44fcce5447a2b757ce403ebb8fc/cell.go#L445

```go
t, v = "str", bstrMarshal(value)

```

![image](https://user-images.githubusercontent.com/12654323/197518747-f42300b7-0693-4f03-9634-2d58869375ca.png)

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Output of `go version`:**

```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. Stream writer writes string cell as `str` type instead of storing the cell value in SST (shared strings table), this avoids operation SST for reduced memory usage and time cost. Yes, this doesn't follow the specification. If you depend on this type or have any other problems, I would consider changing it to the `inlineStr`. But anyway, the normal mode function will store the value in SST, and the cell type in this mode is `s`.

**Comment by eaglexiang** [comment]
In our scene, mem cost of `normal mode` is unacceptable, and `str` is also unacceptable. Could you support `s` in stream write mode? Thanks!

**Comment by xuri** [comment]
I have changed the stream writer to write inline string type for string cell value. Please upgrade to the master branch code, and this change will be released in the next version.

**Comment by eaglexiang** [comment]
Thank you so much! :D
