### ISSUE TITLE
 How to get 0 padded numbers

### ISSUE THREAD

**Issue by rakima5192** [qax-os/excelize#1401]
Hi!

![image](https://user-images.githubusercontent.com/119002043/203837276-9fbb9be4-268a-4435-8c2a-7e7345ea8eb4.png)

![image](https://user-images.githubusercontent.com/119002043/203838999-f16caee8-8313-4791-aebf-641f5d10ec6b.png)

use GetCellValuefunction.

read value is 1.
How can I get 001?

golang version: 1.19.1
excelize version: v2.6.1

Thanks

**Comment by xuri** [comment]
Thanks for your feedback. This issue is similar with #660. The custom number format parser still working in progress, and the library support apply a partial build-in number format. As the documentation of the [`GetCellValue`](https://xuri.me/excelize/ja/cell.html#GetCellValue) function says, if the cell format can be applied to the value of a cell, the applied value will be returned, otherwise, the original value will be returned.

**Comment by xuri** [comment]
I closed this and merged it into issue #660. Please let me know if you have any questions to reopen this anytime.
