### ISSUE TITLE
Get the formatted cell value when setting RawCellValue as true 获取单元格值格式化后的值，设置RawCellValue无效

### ISSUE THREAD

**Issue by abicai** [qax-os/excelize#1446]
![image](https://user-images.githubusercontent.com/36906436/211961621-6498ed14-7857-49d0-a2df-7e9159a7e0ff.png)
例如获取这里面的US$1800 实际得到的是1800 获取不到格式化后的值
		 f.GetCellValue(sheetName,"G10", excelize.Options{
			RawCellValue: true,
		})

**Comment by xuri** [comment]
Thanks for your issue. The field `RawCellValue` is used to specify get the cell value without applying the number format style, so this behavior is in expect, if you wanna get the formatted result, please set the `RawCellValue` value as `false`. In addition, the library support applying partial built-in and custom number format, this feature working in progress, so as the documentation noted, if the cell format can be applied to the value of a cell, the applied value will be returned, otherwise, the original value will be returned. Please also reference issue #660.

**Comment by xuri** [comment]
I closed this issue, if you have any questions, please let me know to reopen this anytime.
