### ISSUE TITLE
xml theme attributes do not meet specification

### ISSUE THREAD

**Issue by y-eight** [qax-os/excelize#1488]
**Description**

As described in the [specification](http://officeopenxml.com/drwSp-styles.php) a theme and its elements should include a leading `a:` in the XML tag e.g. `<a:themeElements>`. Currently, excelize is providing the theme without leading `a:`.

**Steps to reproduce the issue:**
1. create an `.xlsx` file with excelize
2. decompress it
3. have a look at `xl/theme/theme1.xml`
4. compare it with standardisation http://officeopenxml.com/drwSp-styles.php

**Describe the results you received:**

```XML
<?xml version="1.0" encoding="UTF-8"?>
<theme xmlns="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" name="Office Theme">
    <themeElements>
        <clrScheme name="Office">
            <dk1>
                <sysClr val="windowText" lastClr="000000"></sysClr>
            </dk1>
            <lt1>
                <sysClr val="window" lastClr="FFFFFF"></sysClr>
            </lt1>
            <dk2>
                <srgbClr val="44546A"></srgbClr>
            </dk2>
...
```

**Describe the results you expected:**

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<a:theme xmlns="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" name="Office Theme">
    <a:themeElements>
        <a:clrScheme name="Office">
            <a:dk1>
                <a:sysClr val="windowText" lastClr="000000"/>
            </a:dk1>
            <a:lt1>
                <a:sysClr val="window" lastClr="FFFFFF"/>
            </a:lt1>
            <a:dk2>
                <a:srgbClr val="44546A"/>
            </a:dk2>
```

**Output of `go version`:**

```text
go version go1.19 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.7.0
```

**Comment by xuri** [comment]
Thanks for your issue. The XML is compliant with [part 1 of the 5th edition of the ECMA-376 Standard for Office Open XML](https://www.ecma-international.org/publications-and-standards/standards/ecma-376/), according to the [schema of the OOXML](https://github.com/sc34wg4/OOXMLSchemas/blob/master/Part1/OfficeOpenXML-XMLSchema-Strict/dml-main.xsd#L2321-L2330), the namespace prefix a was not required. Because Excelize has made the default namespace of root element `theme` as `http://schemas.openxmlformats.org/drawingml/2006/main`, the child element `themeElements`, `clrScheme`, etc. will be under the same namespace, which semantic was same with namespace represents by prefix a, so I think this needn't be changed. If you still have any problem with this, please let me know.

**Comment by y-eight** [comment]
Thanks for the quick response! I see, sounds legit to me... Unfortunately, I am not familiar with the specification in depth.
I am currently facing a problem reading the xlsx file with another lib ([SheetJS](https://github.com/SheetJS/sheetjs/blob/5b4806bff01a9f4289b4c04e8a60a6c4c52fe93a/bits/49_theme.js#L92-L93)) in my frontend. But this is not your business. I have to check on that side again on how to solve the issue. Thx!

**Comment by y-eight** [comment]
Maybe a further question.
Why is the `theme` element populated with namespaces then?
```XML
<theme xmlns="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" name="Office Theme">
```
I have found an example of my expectations:
For the `solidFill` in `fillStyleLst` the namespace is also not needed, I think (see [here](https://github.com/sc34wg4/OOXMLSchemas/blob/287c5765cf086c51050a84bc3184977c813dd1c5/Part1/OfficeOpenXML-XMLSchema-Strict/dml-main.xsd#L1577-L1585)).

But it is defined in the excelize resulting xlsx theme: `<a:solidFill>`


```<?xml version="1.0" encoding="UTF-8"?>
<theme xmlns="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" name="Office Theme">
    <themeElements>
        <clrScheme name="Office">
         ....   
        <fmtScheme name="Office">
            <fillStyleLst>
                <a:solidFill>
                    <a:schemeClr val="phClr"/>
                </a:solidFill>
                <a:gradFill rotWithShape="1">
                    <a:gsLst>
                        <a:gs pos="0">```

**Comment by xuri** [comment]
Thanks for the feedback. The theme XML has been defined from the [`templateTheme`](https://github.com/qax-os/excelize/blob/dc3bf331d541511a7945b4f3b8eb3e1c98904374/templates.go#L46) constant when you create a new workbook by this library, the namespace prefix `a` has been used for all XML elements in that constant, after runtime's partial load deserialize and serialize, some elements namespace prefix will be removed. But, since the root element has been declared two same namespaces URI: default namespace and the namespace prefix `a`, so all child elements were under the same namespace, even if the element has the namespace prefix `a` or not. In other words, both these two kinds of the element was valid, and it also works in spreadsheet applications.

**Comment by xuri** [comment]
I'll close this issue, if you have any questions, please let me know to reopen this anytime.
