### ISSUE TITLE
Missing Information in Documentation

### ISSUE THREAD

**Issue by teschste-reyrey** [qax-os/excelize#1535]
The current documentation does not provide the following (that I can find)when setting cell Style Alignment:

- Valid values for ReadingOrder.  I assume the values are the Excel constants
   - xlLTR: -5003 (&HFFFFEC75)
   - xlRTL: -5004 (&HFFFFEC74)
   - xlContext: -5002 (&HFFFFEC76)
However in the documentation example it currently shows zero being assigned to ReadingOrder (i.e. unset) but it does not specify what the default value is when that property is left unset.

- Valid values for Indent and RelativeIndent.  They are defined as int values but the docs do not explain if the unit is inches or some other value (unlikely since it is an int).  Are these perhaps really meant to specify Indent Levels?

Any answers you can provide would be helpful, combined with adding that same information to the documentation.

Thanks!

**Comment by xuri** [comment]
Thanks for your issue. Currently, the `ReadingOrder` is an uint64 value indicating whether the reading order (bidirectionality) of the cell is left-to-right, right-to-left, or context dependent.

Accroding the the ISO/IEC 29500:1 (ECMA-376 OOXML) specification §18.8.1, the valid value of `ReadingOrder` was:

0 - Context Dependent - reading order is determined by scanning the text for the first non-whitespace character: if it is a strong right-to-left character, the reading order is right-to-left; otherwise, the reading order left-to-right.
1 - Left-to-Right: reading order is left-to-right in the cell, as in English.
2 - Right-to-Left: reading order is right-to-left in the cell, as in Hebrew.

Indent is an integer value, where an increment of 1 represents 3 spaces. Indicates the number of spaces (of the normal style font) of indentation for text in a cell. The number of spaces to indent is calculated as following:

Number of spaces to indent = indent value * 3

For example, an indent value of 1 means that the text begins 3 space widths (of the normal style font) from the edge of the cell. Note: The width of one space character is defined by the font. Only left, right, and distributed horizontal alignments are supported.

RelativeIndent is an integer value to indicate the additional number of spaces of indentation to adjust for text in a cell.

I'll add this info in the documentation.

**Comment by xuri** [comment]
I have added this missing documentation for these style alignment fields.
