### ISSUE TITLE
How to stream write to a file without consuming too much memory

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1551]
How to stream write to a file without consuming too much memory

**Comment by xuri** [comment]
Thanks for your issue. This issue was duplicated with #1399. Which version of Excelize are you using, how many cells have been written in your spreadsheet, and how much memory usage? Here are some performance figures for your reference: [Performance Figures](https://github.com/xuri/excelize/wiki#performance-figures). Please try using the last version. It seems not have enough info for this issue, so I have closed this, if you have any questions, please let me know, and reopen this anytime.
