### ISSUE TITLE
How to stream read when a file is very large

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1558]
How to stream read when a file is very large

**Comment by xuri** [comment]
Thanks for your issue. This issue was duplicated with #845, #1096, #1220 and #1356. The [row's iterator](https://xuri.me/excelize/zh-hans/sheet.html#Rows) read data as streaming,  it will use lower memory than `GetRows`. I've closed this, if you have any question please let me know, and you can reopen this anytime.
