### ISSUE TITLE
how to set fill color with  alpha

### ISSUE THREAD

**Issue by 13100967125** [qax-os/excelize#1583]
i use excelHandler.NewStyle func to set style ,i use #f5222d4d color to set fill style ,but it only can show #f5222d , alpha do not work

**Comment by xuri** [comment]
Thanks for your issue. Spreadsheet doesn't use transparency for cell borders and fill colors because there can't be anything behind a cell to see through the transparency, that is, cells are the bottom layer. Transparency can be applied to shapes, but which are not represented by color alpha. I've closed this issue if you have any questions, please let me know, and reopen this anytime.
