### ISSUE TITLE
Set data validation of a partial column/row cells 设置列校验时，如何设置从某一列的第几行到这一列结尾都需要校验？

### ISSUE THREAD

**Issue by ZQHcode** [qax-os/excelize#1589]
目前的场景类似于：对于A列，从他的第6行开始，到最后一行需要设置校验；如果直接validation.SetSqref("A:A")，那么前五行的单元格也会被设置校验，这是不需要看到的，请问可以如何处理呢

**Comment by xuri** [comment]
This issue was similar with #1576. As the documentation says, you can set the data validation range by the [`Sqref`](https://xuri.me/excelize/en/data.html#AddDataValidation) field. You can set data validation of a partial column/row cells in column A with maximum rows constants ([`excelize.TotalRows`](https://xuri.me/excelize/en/constants.html?h=TotalRows)) reference`A6:A1048576` (columns A and B `A1:B1048576`).

**Comment by xuri** [comment]
This issue was similar with #1576. As the documentation says, you can set the data validation range by the [`Sqref`](https://xuri.me/excelize/en/data.html#AddDataValidation) field. You can set data validation of a partial column/row cells in column A with maximum rows constants ([`excelize.TotalRows`](https://xuri.me/excelize/en/constants.html?h=TotalRows)) reference`A6:A1048576`.

**Comment by xuri** [comment]
I've closed this issue, if you have any questions, please let me know to reopen this anytime.
