### ISSUE TITLE
What is the purpose of the temporary files in the "/tmp" directory

### ISSUE THREAD

**Issue by zy-repo** [qax-os/excelize#1596]
Use the following method to generate excel, There are large temporary files in the "/tmp" directory, as shown in the figure. What are the functions of these temporary files? Can we control the automatic deletion after the files are generated?
```go
	excel := excelize.NewFile()
	streamWriter, _ := excel.NewStreamWriter("Sheet1")

	for i := 2; i < 10000; i++ {
		data := make([]interface{}, 0)
		for i := 0; i < 800; i++ {
			data = append(data, 100)
		}
		_ = streamWriter.SetRow("A"+strconv.Itoa(i), data)
	}

	streamWriter.Flush()
	excel.SaveAs(prefix + "stream.xlsx")
```

<img width="343" alt="image" src="https://github.com/qax-os/excelize/assets/103711275/d8292414-bc9b-491f-b936-a49df095f7cd">

**Comment by xuri** [comment]
Thanks for your issue. Please reference the documentation, since Excelize v2.5.0, you need to using [`Close`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.Close) function to closes and cleanup the open temporary file for the spreadsheet after save the workbook. I closed this issue, if you have any questions, please let me know and reopen this anytime.
