### ISSUE TITLE
mergeCell doesn't  seems to work

### ISSUE THREAD

**Issue by zy-repo** [qax-os/excelize#1601]
as the code shown below, the file generated doesn't merge A1:G1.

```
package main

import (
	"fmt"
	"strconv"
	"time"

	"github.com/xuri/excelize/v2"
)

func main() {
	excel := excelize.NewFile()
	defer excel.Close()

	if err := addTitle(excel); err != nil {
		fmt.Println(err)
	}

	if err := modifyStyle(excel); err != nil {
		fmt.Println(err)
	}

	if err := excel.SaveAs(strconv.Itoa(time.Now().Second()) + ".xlsx"); err != nil {
		fmt.Print(err)

	}
}

func addTitle(f *excelize.File) error {
	streamWriter, err := f.NewStreamWriter("Sheet1")
	if err != nil {
		return err
	}

	metaData := [][]interface{}{
		{"标题"},
	}

	for i := 1; i <= len(metaData); i++ {
		_ = streamWriter.SetRow("A"+strconv.Itoa(i), metaData[i-1])
	}

	if err = streamWriter.Flush(); err != nil {
		return err
	}

	return nil
}

func modifyStyle(f *excelize.File) error {
	err := f.MergeCell("Sheet1", "A1", "G1")
	if err != nil {
		return err
	}

	return nil
}

```

<img width="342" alt="image" src="https://github.com/qax-os/excelize/assets/103711275/e6583219-8e9a-4023-ac08-36bbcc67e981">

**Comment by xuri** [comment]
Thanks for your issue. Please reference the [documentation](https://xuri.me/excelize/en/stream.html#NewStreamWriter), as the documentation says: "the normal mode functions and stream mode functions can not be work mixed to writing data on the worksheets". Please use the `streamWriter.MergeCell` function to merge cells in the stream or use the normal mode `f.SetSheetRow` function instead of stream writer.
