### ISSUE TITLE
csv  to excel

### ISSUE THREAD

**Issue by quanxiangsheng** [qax-os/excelize#1635]
Can the library write csv files to excel? When I try to open the csv file, I get an error 'zip: not a valid zip file'

```go 
f, err := excelize.OpenFile("./testCsv.csv")
	if err != nil {
		fmt.Println("Failed to open CSV file:", err)
		return
}

**Comment by xuri** [comment]
Thanks for your issue. If you are reporting a new issue, make sure that we do not have any duplicates already exist. This issue was duplicate with #1496. You can handle CSV/TSV file with Go [encoding/csv](https://pkg.go.dev/encoding/csv) package. I've closed this, if you have any question, please let me know, and you can reopen this anytime.
