### ISSUE TITLE
Can't read column with custom number format.

### ISSUE THREAD

**Issue by peacewalker122** [qax-os/excelize#1658]
**Description**
Can't read column with custom number format. specifically #

**Steps to reproduce the issue:**
1. Create a xlsx file with some column using custom number format in my case #

**Describe the results you received:**
only got the column without custom number format
**Describe the results you expected:**

**Output of `go version`:**
1.21

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux

**Comment by xuri** [comment]
Thanks for your issue. There are some incompatible changes in the Go 1.21.0, the Excelize library can not work with that version normally. If you are using the Go 1.21.x, please upgrade to the Go 1.21.1 and later version. I have added notice on the [README](https://github.com/xuri/excelize#introduction) and [documentation website](https://xuri.me/excelize/en/base/installation.html#install) for this. In addition, as the documentation of the `GetCellValue` says, if the cell format can be applied to the value of a cell, the applied value will be returned, otherwise, the original value will be returned. We need to know exactly the custom number format code in your case, if you still got this problem in Go 1.21.1, please provide a standalone example program or reproducible demo if you can.

**Comment by peacewalker122** [comment]
## using 1.21.1 same case happening

## custom format that i mention
![number custom format](https://github.com/qax-os/excelize/assets/81625151/aa472f04-ac86-473c-b21b-30a8d17eff58)

## code example
```
f, err := excelize.OpenReader(fileBody)
if err != nil {
	return err
}

rows, err := f.GetRows("Sheet1")
if err != nil {
        return err
}

for i,row := range rows{
	// Do Something
}
```

**Comment by xuri** [comment]
Thanks for your feedback. Could you provide a workbook as a file attachment without confidential info to reproducible this problem?

**Comment by peacewalker122** [comment]
[example.xlsx](https://github.com/qax-os/excelize/files/12596992/example.xlsx)

note: the custom format on number column

**Comment by xuri** [comment]
I have fixed this issue, please try to upgrade the master branch code, and this patch will be released in the next version.

**Comment by deanx3** [comment]
Hey @xuri , i am using excelize/v2, will this bug be fixed in that version as well? as i am facing the same issue
Thanks in advance

**Comment by xuri** [comment]
Hi @deanx3, you can upgrade your Excelize module to the master branch to apply this patch by following command:

```bash
go get -u github.com/xuri/excelize/v2@master
```
