### ISSUE TITLE
PivotTable corrupts Excel file when it contains ~50000 records, it is not if it contains ~25000 records

### ISSUE THREAD

**Issue by mokalovesoulmate** [qax-os/excelize#1679]
Hello! First of all, thanks for the excellent library.

**Description**

**Steps to reproduce the issue:**
1. Generate an Excel file with 25000 or 50000 records of data * 13 columns. I inserted the whole thing using `NewStreamWriter`.
2. Use `AddPivotTable` to create a Pivot Table based on existing data. 
3. Open the Excel file.

**Describe the results you received:**
1. While opening Excel with 25000 data, it works just fine.
2. While opening Excel with 50000 data, Excel says the document is corrupted. Excel asks to repair it, but when successfully repaired, it actually removed the Pivot Table.

**Describe the results you expected:**
No matter the data size, or at least the [limitations specified](https://support.microsoft.com/en-gb/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3) by Microsoft, the Excel file should be able to be opened normally.

**Output of `go version`:**

```text
go version go1.21.1 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
OS/Hardware: MacBook Air M1, Mac OS Sonoma
Excel: 16.77.1 from Office 365

**Comment by xuri** [comment]
Thanks for your issue. There are two kinds of functions in the excelize library: normal mode functions and stream mode functions. The `AddPivotTable` function is a normal mode function, and the `NewStreamWriter` is a stream mode function. These two kinds of functions can not be used mixed. The stream mode function is used to generate a worksheet with the amount of data in lower resource usage, this library doesn't support create pivot table in stream mode currently, so please set the cell data with normal mode function `SetCellValue` or `SetSheetRow` instead of the stream mode function.

**Comment by xuri** [comment]
As the documentation says, the normal mode function and stream mode functions can not be used mixed. If you reopen the workbook generated by the stream mode function and then use the normal mode function for this workbook, the memory usage is almost the same as using the normal mode function, so the stream mode generation is no longer required.

**Comment by mokalovesoulmate** [comment]
Yes thank you for your advice. I just tried my own method above and it is solving my problem. However I will considering using normal `SetCellValue`/`SetSheetRow` as you suggest if I want to take memory consumption into consideration.

Thanks!
