### ISSUE TITLE
Hash of identical files

### ISSUE THREAD

**Issue by Levap123** [qax-os/excelize#1732]
Hello excelize team,

I am currently working with the excelize library and have encountered a scenario where I need to generate Excel files that are identical in every respect, such that their SHA256 hashes would also be identical. However, I've observed that even when creating new files with the same content and structure, the resulting SHA256 hashes are different for each file.

This leads me to wonder whether excelize adds any unique metadata or data (such as timestamps or unique identifiers) to each file during creation, which might be causing this discrepancy in hashes.

Could you please provide some insights on the following:
- Does excelize inherently include any unique data or metadata in each new Excel file it creates?
-  If so, is there a way to control or disable this behavior to ensure that two identically created files using excelize would yield the same SHA256 hash?

**Comment by xuri** [comment]
Thanks for your issue. We've been using the `sync.Map` to store workbook [packages each part](https://github.com/qax-os/excelize/blob/866e7fd9e1d09e79b9ff345f240e10a72ed9f310/file.go#L204) path name and content internally, so the order of these parts may be different on the save, that's the reason for this problem. I'll consider changing this design, but that needs some time. I suggest that make a copy of the workbook instead of saving it as a new one for the same workbook if you can.

**Comment by xuri** [comment]
Thanks for your issue. We've been using the `sync.Map` to store workbook [packages each part](https://github.com/xuri/excelize/blob/866e7fd9e1d09e79b9ff345f240e10a72ed9f310/file.go#L204) path name and content internally, so the order of these parts may be different on the save, that's the reason for this problem. I'll consider changing this design, but that needs some time. I suggest that make a copy of the workbook instead of saving it as a new one for the same workbook if you can.

**Comment by user65536** [comment]
@xuri I've created a pull request for this issue, the internal part path has been sorted so that the output file would be identical.

**Comment by tjayrush** [comment]
This feature is HUGE. Thanks for including this. We publish Excel sheets from a process that starts with blockchain data (that, as you probably know) is hashed data. Until now, we would arrive all the way at the end of a lengthy data extraction pipeline that preserves the "hashed data nature" of the blockchain data, but when we wrote to Excel using your library, it would destroy that preserved nature of the hashable data.

We do all this so we can store the Excel file on IPFS which is a hash-based, content addressable storage medium. Our pipeline can now produce perfectly auditable and re-procucible data all the way from the blockchain into an Excel spreadsheet. SUPER useful. THanks.
