### ISSUE TITLE
Go mod

### ISSUE THREAD

**Issue by rmasci** [qax-os/excelize#1744]
Go mod nightmares

I can't use the package!  When I go to include github.com/qax-os/excelize it tells me the module declares its path as github.com/360EntSecGroup-Skylar/excelize

So I do a go get github.com/360EntSecGroup-Skylar/excelize it tells me that module declares it's self as 
github.com/xuri/excelize/v2

If I use that as my import path it fails too. This project has passed through many different repositorys, wouldn't it be a good idea to make sure the go.mod file works?

**Steps to reproduce the issue:**
1. go get github.com/qax-os/excelize
2. go get github.com/360EntSecGroup-Skylar/excelize
3. go get github.com/xuri/excelize/v2

can't get the package to work in IDE

```text
go 1.21.4
```

**Excelize version or commit ID:**

```text
v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. I'm sorry for causing you confusion, this issue is related to #522, #973, #1020, #1079 and #1472. The new go modules import path `github.com/xuri/excelize/v2` took effect since version 2.4.1, please use this URL. I've closed this issue, if you have questions, please let me know, and you can reopen this anytime.
