### ISSUE TITLE
使用SetDefinedName无法正常设置打印区域

### ISSUE THREAD

**Issue by Lucky759** [qax-os/excelize#1765]
**Description**

**Steps to reproduce the issue:**
1. 
```
	if err := f.SetDefinedName(&excelize.DefinedName{
		Name:     "_xlnm.Print_Area",
		RefersTo: "Sheet1!$A$1:$J$25",
		Scope:    "Sheet1",
	}); err != nil {
		fmt.Println(err)
	}
```
2.
3.

**Describe the results you received:**
invalid name "_xlnm.Print_Area", the name should be starts with a letter or underscore, can not include a space or character, and can not conflict with an existing name in the workbook
**Describe the results you expected:**
这个命名似乎没有问题，并且如果不使用这个命名，无法使得打印区域设置生效。
**Output of `go version`:**
v2.8.0
```text
(paste your output here)
```

**Excelize version or commit ID:**

```text
(paste here)
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment]
Thanks for your issue. This problem already has been fixed by commit [ae64bca](https://github.com/xuri/excelize/commit/ae64bcaabea65d9bafa4eed1753ca961f2f5e9c2), please upgrade to the master branch code, and this patch will be released in the next version. I've closed this issue, if you have any questions, please let me know, and you can reopen this anytime.

**Comment by Lucky759** [comment]
更新后name的问题得到了解决，但我还有1个疑问：
只有往name中传入_xlnm.Print_Area时，打印区域才会生效，但示例中并没有相关说明。

**Comment by xuri** [comment]
What are the results you expected? Here is a [Simplified Chinese version docs](https://xuri.me/excelize/zh-hans/workbook.html#SetDefinedName) for your information.
