### ISSUE TITLE
Invisible chart on excel after StreamWriter writing data

### ISSUE THREAD

**Issue by joycemcliu** [qax-os/excelize#1766]
**Description**

**Steps to reproduce the issue:**
1. writing data using StreamWriter
2. end the streaming writing process by `Flush()`
3. add a chart using those data and save as `.xlsx` file 

**Describe the results you received:**
Open that file using excel, can't see that char; but using macOS's Numers can see the chart

**Describe the results you expected:**

**Output of `go version`:**
```text
go version go1.21.4 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Microsoft Excel for Mac: Version 16.78.3 (23102801)  

**Reproducing code:**
```go
package main

import (
	"fmt"

	"github.com/xuri/excelize/v2"
)

func main() {
	f := excelize.NewFile()
	defer func() {
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()

	sw, err := f.NewStreamWriter("Sheet1")
	if err != nil {
		fmt.Println(err)
		return
	}

	for idx, row := range [][]interface{}{
		{nil, "Apple", "Orange", "Pear"}, {"Small", 2, 3, 3},
		{"Normal", 5, 2, 4}, {"Large", 6, 7, 8},
	} {
		cell, err := excelize.CoordinatesToCellName(1, idx+1)
		if err != nil {
			fmt.Println(err)
			return
		}
		if err := sw.SetRow(cell, row); err != nil {
			fmt.Println(err)
			return
		}
	}
	sw.Flush()
	if err := f.AddChart("Sheet1", "E1", &excelize.Chart{
		Type: excelize.Col3DClustered,
		Series: []excelize.ChartSeries{
			{
				Name:       "Sheet1!$A$2",
				Categories: "Sheet1!$B$1:$D$1",
				Values:     "Sheet1!$B$2:$D$2",
			},
			{
				Name:       "Sheet1!$A$3",
				Categories: "Sheet1!$B$1:$D$1",
				Values:     "Sheet1!$B$3:$D$3",
			},
			{
				Name:       "Sheet1!$A$4",
				Categories: "Sheet1!$B$1:$D$1",
				Values:     "Sheet1!$B$4:$D$4",
			}},
		Title: []excelize.RichTextRun{
			{
				Text: "Fruit 3D Clustered Column Chart",
			},
		},
	}); err != nil {
		fmt.Println(err)
		return
	}
	if err := f.SaveAs("Book1.xlsx"); err != nil {
		fmt.Println(err)
	}

}

```

**Comment by xuri** [comment]
Thanks for your issue. There are two kinds of functions in the excelize library: normal mode functions and stream mode functions. The AddChart function is a normal mode function, and the NewStreamWriter is a stream mode function. These two kinds of functions can not be used mixed. The stream mode function is used to generate a worksheet with the amount of data in lower resource usage, this library doesn't support create chart in stream mode currently, so please set the cell data with normal mode function SetCellValue or SetSheetRow instead of the stream mode function. Please also reference issue #1679.

**Comment by xuri** [comment]
I'll close this issue, if you have any questions, please let me know to reopen this anytime.
