### ISSUE TITLE
Different gradient fill colors return the same style index

### ISSUE THREAD

**Issue by edwardfward** [qax-os/excelize#1820]
Different gradient fills produce the same style index making it impossible to use more than one gradient fill in a workbook.

```go
package main

import (
	"fmt"
	"github.com/xuri/excelize/v2"
)

func main() {
	f := excelize.NewFile()

	s1 := excelize.Style{
		Fill: excelize.Fill{
			Type:    "gradient",
			Pattern: 1,
			Shading: 1,
			Color:   []string{"#000000", "#FFFFFF"},
		},
	}

	s2 := excelize.Style{
		Fill: excelize.Fill{
			Type:    "gradient",
			Pattern: 1,
			Shading: 1,
			Color:   []string{"#FFFF00", "#000000"},
		},
	}

	s1Index, _ := f.NewStyle(&s1)
	s2Index, _ := f.NewStyle(&s2)

	fmt.Println("s1Index:", s1Index)
	fmt.Println("s2Index:", s2Index)
}

```

**Describe the results you received:**

```bash
s1Index: 1
s2Index: 1
```

**Describe the results you expected:**
```bash
s1Index: 1
s2Index: (Something other than 1)
```

**Output of `go version`:**

```text
go version go1.22.0 darwin/arm64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.8.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

```text
Apple M2 Max (Mac OS 14.2.1)
```

**Comment by xuri** [comment]
Thanks for your issue. I have tested with the v2.8.0, and it works well. This bug was introduced by commit [`9c079e5`](https://github.com/xuri/excelize/commit/9c079e5eec19a94553c6a1e5389be375e38a9446#diff-1568c4b99859854b2be65ef43c383aefa000ee6be64fede7b0cd039a708d1bff). We need to change the array variable `styleFillVariants` to a function to fix this:

```go
styleFillVariants = func() []xlsxGradientFill {
    return []xlsxGradientFill{
        // ...
    }
}
```

Would you like to create a pull request to help us fix this problem?

**Comment by edwardfward** [comment]
I will give it a go.
