### ISSUE TITLE
RemoveCol return error: errors.errorString{s:"the column number must be greater than or equal to 1 and less than or equal to 16384"}

### ISSUE THREAD

**Issue by jianxinhou** [qax-os/excelize#1827]
**Description**
当我执行以下代码时：
```golang
func TestBug(t *testing.T) {
	bs, err := os.ReadFile("./test2.xlsx")
	assert.Nil(t, err)
	file, err := OpenReader(bytes.NewReader(bs))
	assert.Nil(t, err)

	err = file.RemoveCol("Sheet1", "A")
	assert.Nil(t, err)}
}
```
使用的xlsx文件如下：
[test2.xlsx](https://github.com/qax-os/excelize/files/14417236/test2.xlsx)

似乎是因为在这个函数中：
![image](https://github.com/qax-os/excelize/assets/51222175/5882bcda-311a-4fac-96e0-a6f645a49fed)
`col += offset`后`col == 0`导致了该报错

**Describe the results you received:**
```shell
--- FAIL: TestBug (11.20s)
    excelize_test.go:1723: 
        	Error Trace:	/Users/XXX/go/src/github.com/qax-os/excelize/excelize_test.go:1723
        	Error:      	Expected nil, but got: &errors.errorString{s:"the column number must be greater than or equal to 1 and less than or equal to 16384"}
        	Test:       	TestBug
FAIL
```

**Describe the results you expected:**

PASS

**Output of `go version`:**

```text
go version go1.21.6 darwin/arm64
```

**Excelize version or commit ID:**

```text
688808b2b4f7bb1f338991c810cd2ee6a7bb1451
```

**Comment by xuri** [comment]
Thanks for your issue. This bug was introduced by commit [9c079e5](https://github.com/xuri/excelize/commit/c7acf4fafef429b67ca79f496d2709271c840dcd). This issue has been fixed, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.

**Comment by xuri** [comment]
Thanks for your issue. This bug was introduced by commit [c7acf4f](https://github.com/xuri/excelize/commit/c7acf4fafef429b67ca79f496d2709271c840dcd). This issue has been fixed, please upgrade to the master branch by `go get -u github.com/xuri/excelize/v2@master`, and this patch will be released in the next version.
