### ISSUE TITLE
会提供 Max row  Max col 属性吗

### ISSUE THREAD

**Issue by shzy2012** [qax-os/excelize#1876]
后续会提供如下功能吗
1. 最大行数 Max row   
2. 最大列数 Max col

**Comment by xuri** [comment]
Thanks for your issue. This was duplicated with issue #1402. Due to the principle of minimum availability, there is no plan to introduce this feature to keep the library core and easy. But you can easily know max rows and columns by iterating and counting row/column numbers with the existing functions. I'll close this issue. If you have any questions, please let me know, and you can reopen this anytime.
