### ISSUE TITLE
Excelize v2.8.1 is causing process restart with performance data  

### ISSUE THREAD

**Issue by yflufdvil** [qax-os/excelize#1916]
Hi, 
We are using Excelize v2.8.1 , and we have observed a process restart with this version of Excelize on performance data, same process with same data is working fine with version v2.7.1 , 
It might be a memory leak or some other issue because we have not observed panic error as well, but process is restarting.  

Function used --> 
excelize.OpenFile
GetRows 
Close()

What is the EOL criteria for version v2.7.1
Can you please check?

**Comment by xuri** [comment]
Thanks for your issue. This issue was introduced by commit for fix #1692 in v2.8.1, and has been fixed by PR #1849, please upgrade to the master branch code, and this path will be released in the next version. Here is a benchmark for your information. I've closed this. if you have any questions, please let me know.
