### ISSUE TITLE
Retaining Cell Styles While Changing Background Color with SetCellStyle

### ISSUE THREAD

**Issue by stephsix** [qax-os/excelize#2050]
**Description**

When using the SetCellStyle method, I’ve noticed that it overwrites all the existing styles of the cell. Is there a way to change the cell’s background color while preserving other cell styles (such as font, conditional formatting, bolding, etc.)?

**Describe the results you received:**

I used SetCellStyle to change the background color of cell A5, and then it lost the valid decimal format. 
<img width="143" alt="image" src="https://github.com/user-attachments/assets/b2988737-5c6c-4dd9-8db4-e32e7fa54858" />

**Describe the results you expected:**

**Output of `go version`:**
My expectation is like this:
<img width="142" alt="image" src="https://github.com/user-attachments/assets/0c02d3f2-5755-42bf-929b-348cd1aaab0a" />

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
go 1.16 github.com/360EntSecGroup-Skylar/excelize v1.4.1

**Comment by xuri** [comment]
This duplicated with issue #1520. As the documentation says: "SetCellStyle will overwrite the existing styles for the cell, it won't append or merge style with existing styles". The new function `GetStyle` has been added since version 2.8.0. Please upgrade to the lasted version, so you can change the style of cell by following steps:

- Get style ID of a cell by `GetCellStyle` function
- Get style definition by style ID via `GetStyle` function
- Change the style
- Create new style by `NewStyle` function to get a new style ID
- Set cells style with style ID by `SetCellStyle` function

So, I will close this. If you have any questions, please let me know and reopen this anytime.
