### ISSUE TITLE
Chart style

### ISSUE THREAD

**Issue by joker63** [qax-os/excelize#229]
How to set the style of the graph? I need to change the color and add lines.
This default chart http://prntscr.com/jr2a8c
need a http://prntscr.com/jr2b0k

**Comment by stdatiks** [comment]
+1
need it too

**Comment by byteman** [comment]
大神，图表横纵坐标标签颜色太浅这个有办法解决吗？？

xmlCharte.go
1192:
LumMod: &attrValInt{Val: 15000},
LumOff: &attrValInt{Val: 85000},

这里透明度定义 参考https://stackoverflow.com/questions/19886180/whats-the-difference-between-lummod-lumoff-and-tint-shade-in-drawingml-colors

luminance = (luminance/100)*(lumMod/100_000) + (lumOff/100_000)
根据公式修改85000->15000减小

**Comment by xuri** [comment]
Sorry for the late reply. The `AddChart` function support custom chart axis font style since v2.7.0 (reference issues #320 and #378), and support to set custom series (bar, line, etc.,) color in the charts (reference issues #1345 and #1474). I've closed this issue, please upgrade to the latest version, and if you have any question, please let me know, and you can reopen this anytime.
