### ISSUE TITLE
Add more line chart style properties settings support

### ISSUE THREAD

**Issue by byteman** [qax-os/excelize#402]
希望能够设置更丰富的折线图的样式，比如每个点的大小样式，平滑样式等等

**Comment by xuri** [comment]
Thanks for your issue. Sorry for the late reply. Excelize library support to set marker type and custom line width since [v2.3.2](https://github.com/xuri/excelize/releases/tag/v2.3.2), relate issues #549 and #657, and support specify if the smooth line of the line chart since version [v2.7.0](https://github.com/xuri/excelize/releases/tag/v2.7.0), related issue #1290. I've closed this issue, if you have any feedback please let me know, and reopen this anytime.
